api_key_mq = "hn3cnNt2TJoLZTi2yNUY3oxe2LK0pE0w"

neighborhoods_dc = [
    "Takoma Park",
    "Catholic University-Brookland",
    "Anacostia",
    "Shaw",
    "Stadium-Armory",
    "Logan Circle",
    "Ledroit Park",
    "Chevy Chase",
    "Barnaby Woods",
    "Capitol Hill",
    "Friendship Heights",
    "Au-Tenleytown",
    "The Palisades",
    "Cleveland Park",
    "Downtown",
    "Columbia Heights",
    "Fort Totten-Upper Northeast",
    "Deanwood",
    "Adams Morgan",
    "Petworth",
    "Foxhall Village",
    "Glover Park",
    "Kalorama",
    "Brentwood",
    "Mount Vernon Square",
    "Woodley Park",
    "Georgetown",
    "Foggy Bottom",
    "Berkley",
    "Mount Pleasant",
    "U Street Corridor",
    "South West",
    "Brightwood",
    "Dupont Circle"
]

num_traffic_trips = 2000
restrict_traffic_trips = 10000000000000

poi_categories = ["Wineries",
"Transportation Services",
"Taxis",
"Food Markets",
"Convenience Stores",
"Grocery Stores",
"Grocers Health Foods",
"Seafood Markets",
"Farm Markets",
"Bakers Cake & Pie",
"Doughnuts",
"Miscellaneous Food Stores",
"Electric Charging Station",
"Children's Clothing",
"Clothing Retail",
"Rubber & Plastic Footwear Retail",
"Sportswear",
"Ice Cream Parlors",
"Foods Carry Out",
"All) Restaurants",
"Delicatessens",
"Cafeterias",
"Cafes",
"Appetizers & Snacks Etc",
"Subs & Sandwiches",
"Theatres Dinner",
"Coffee Shops",
"Tea Rooms",
"Juice Bars",
"Restaurants Cyber Cafes",
"Bars",
"Discotheques",
"Cocktail Lounges",
"Pubs",
"Comedy Clubs",
"Karaoke Clubs",
"Pharmacies",
"Wines Retail",
"Flea Markets",
"Book Stores",
"Toy Stores",
"Gift Shops",
"Art Galleries & Dealers",
"Monuments",
"Shopping Centers & Malls",
"Hotels & Motels",
"Cottages & Cabins",
"Bed & Breakfasts",
"Chalet & Cabin Rentals",
"Skiing Centers & Resorts",
"Resorts",
"Villas",
"Hostels",
"Adventure Games & Activities",
"Campgrounds",
"Manicurists",
"Barbers",
"Movie Theatres",
"Movie Theatres (drive-Ins)",
"Theatres Live",
"Concert Venues",
"Entertainment Bureaus",
"Bowling Centers",
"Stadiums Arenas & Athletic Fields",
"Race Tracks",
"Horse Racing",
"Health Clubs & Gyms",
"Golf Courses-Public Or Private",
"Casinos",
"Arcades",
"Amusement Places",
"Water Parks",
"Amusement Parks",
"Recreation Centers",
"Hockey Clubs",
"Flying Clubs",
"Beach & Cabana Clubs",
"Sports Recreational",
"Skating Rinks",
"Bicycles Renting",
"Baths Bath Houses Spas & Saunas",
"Billiard Parlors",
"Fairgrounds",
"Historical Places",
"Parks",
"Picnic Grounds",
"Horseback Riding",
"Swimming Pools Public",
"Tennis Courts Public",
"Squash Courts Public",
"Colleges & Universities",
"Hiking Backpacking & Mountaineering Service",
"Museums",
"Planetariums",
"Cultural Centres",
"National Monuments",
"Zoos",
"Arboretums",
"Aquariums Public",
"Motoring Organisations",
"Clubs",
"Community Organizations",
"All) Places Of Worship",
"Dance Clubs",
"Beach",
"Cave",
"Forest",
"Ridge",
"Valley",
"Bay",
"Rapids",
"Reservoir",
"Swamp",
"Bridge",
"Building",
"Dam",
"Tower",
"Tourist Attra"]

# categories = [
#     "bar", "book_store", "cafe", "casino", "clothing_store", "convenience_store", "movie_theater", "museum", "night_club", "park", "restaurant", "shopping_mall", "spa", "stadium", "store", "supermarket", "tourist_attraction", "university"
# ]
#
# ]

categories = [

]
